server:
  port: 8080

spring:
  application:
    name: xc-test-freemarker
  freemarker:
    cache: false #关闭模板缓存
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便 进行模板测试
  data:
    mongodb:
      uri: mongodb://admin:admin@192.168.80.190:27017
      database: xc_cms