server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://192.168.80.190:3306/xc_course?characterEncoding=utf-8
      username: root
      password: root@wsx86
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper-dialect: mysql

#  eureka配置信息
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
  instance:
    prefer-ip-address: true # 将自己的ip地址注册到eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定服务的实例id
# ribbon 负载均衡的设置
ribbon:
  MaxAutoRetries: 2                # 最大重试次数 （当服务列表中可以查找到服务，连接失败的时候会重试）
  MaxAutoRetriesNextServer: 3      # 切换实例的重试次数
  OkTORetryOnAllOpearations: false # 对所有的请求都进行重试，如果是get请求是可以的，但是如果是post,put,等操作，
                                   # 在没有实现幂的情况下是很危险的，设置为false
  ConnectTimeout: 5000             # 连接超时时间
  ReadTimeout: 6000                # 请求处的超时时间

# 课程预览发布的相关配置
course-publish:
  siteId: 5a751fab6abb5044e0d19ea1
  templateId: 5a925be7b00ffc4b3c1578b5
  previewUrl: http://www.xconline.edu/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /static/course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/